const PDFDocument = require('pdfkit');

const generateNumerologyPDF = (userData, apiData) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, bufferPages: true });
            let chunks = [];

            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', (err) => reject(err));

            // Title
            doc.fillColor('#B08D57').fontSize(26).text('Complete Numerology Report', { align: 'center' });
            doc.moveDown();

            // User Details Section
            doc.fillColor('#333333').fontSize(18).text('User Details', { underline: true });
            doc.fontSize(12).text(`Full Name: ${userData.fullName}`);
            doc.text(`Email: ${userData.email}`);
            doc.text(`Date of Birth: ${userData.dob}`);
            doc.text(`Gender: ${userData.gender || 'N/A'}`);
            doc.text(`Location: ${userData.location || 'N/A'}`);
            doc.moveDown();

            // Numerology Insights Section
            doc.fillColor('#333333').fontSize(18).text('Numerology Insights', { underline: true });
            doc.moveDown(0.5);

            // Dynamically render insights from API data
            if (apiData && typeof apiData === 'object' && Object.keys(apiData).length > 0) {
                Object.entries(apiData).forEach(([key, value]) => {
                    // Skip entries with errors or empty data
                    if (!value || value.error) return;

                    const formattedKey = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
                    doc.fillColor('#B08D57').fontSize(14).text(formattedKey);
                    
                    if (typeof value === 'object' && value !== null) {
                        // Attempt to display name/description if present, otherwise stringify
                        if (value.name || value.description || value.text || value.detailed_meaning) {
                            if (value.name) doc.fillColor('#444444').fontSize(12).text(`Result: ${value.name}`);
                            const mainText = value.detailed_meaning || value.description || value.text;
                            if (mainText) {
                                doc.fillColor('#666666').fontSize(10).text(mainText, { align: 'justify' });
                            }
                            
                            // Handle summary object if it exists (Dakidarts often has this)
                            if (value.summary && typeof value.summary === 'object') {
                                if (value.summary.overview) {
                                    doc.fillColor('#444444').fontSize(11).text('Overview', { underline: true });
                                    doc.fillColor('#666666').fontSize(10).text(value.summary.overview);
                                }
                                if (value.summary.strengths && Array.isArray(value.summary.strengths)) {
                                    doc.fillColor('#444444').fontSize(11).text('Strengths:');
                                    value.summary.strengths.forEach(s => doc.fillColor('#666666').fontSize(9).text(`• ${s}`));
                                }
                            }
                        } else {
                            doc.fillColor('#666666').fontSize(10).text(JSON.stringify(value, null, 2));
                        }
                    } else {
                        doc.fillColor('#666666').fontSize(11).text(String(value));
                    }
                    doc.moveDown(1.5);
                });
            } else {
                doc.fillColor('#666666').fontSize(11).text('No detailed insights available at this moment.');
            }

            // Footer - Apply to all buffered pages
            const range = doc.bufferedPageRange();
            for (let i = range.start; i < range.start + range.count; i++) {
                doc.switchToPage(i);
                doc.fontSize(10).text(
                    `Generated by Numerology Project - Page ${i + 1}`,
                    50,
                    doc.page.height - 50,
                    { align: 'center', width: doc.page.width - 100 }
                );
            }

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generateNumerologyPDF };
